services:
  tcflask:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./.env
    depends_on:
      tcdata:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      uv run flask run
      --host 0.0.0.0
      --port 5000

  tcdata:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
