"""add is_published to post

Revision ID: 9bcfed102a42
Revises:
Create Date: 2026-03-07 02:36:51.240967

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9bcfed102a42"
down_revision: Union[str, Sequence[str], None] = "0001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "post",
        sa.Column("is_published", sa.Boolean(), nullable=False, server_default="false"),
    )
    op.alter_column("post", "is_published", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "is_published")
    # ### end Alembic commands ###
